### ISSUE TITLE
Bug? Weitere Beiträge

### ISSUE THREAD

**Issue by strikerboy1024** [prof-membrane/plugin.video.ardmediathek_de#1]
Der Punkt "Weitere Beitrage" in den Menüs funktioniert hier zur Zeit allgemein nicht. Gleiches gilt für das ZDF Addon. (Krypton, Confluence/Estuary)

**Comment by prof-membrane** [comment]
Oha, ist mir durch die Lappen gegangen als ich experimentiert hab. Fehler war in der libMediathek. Fix ist oben.
