### ISSUE TITLE
Listen laden nicht mehr

### ISSUE THREAD

**Issue by mfxbe** [prof-membrane/plugin.video.ardmediathek_de#11]
Wenn ich das Addon öffnen will passiert nichts, aufrufen über das eingerichtete Hub hingegen scheint noch zu funkionieren.

Logdatei

_Edit: Vernünftiges Protokoll siehe unten_

System ist LibreElec 7.90. Melde das jetzt mal hier aber der Fehler tritt auch in anderen Mediatheken auf.

**Comment by prof-membrane** [comment]
Ich kann nichts feststellen, das Log ist einfach nur eine Ansammlung von Zeichen.

**Comment by mfxbe** [comment]
Ja, sorry. Die hats irgendwie verhauen. Man sollte keine Bugreports schreiben wenn man's eilig hat.

Habs [hier](https://github.com/prof-membrane/plugin.video.ardmediathek_de/files/709419/kodi-log.txt) nochmal vernünftig angehangen. Die Fehler fangen so um Zeile 143 an.

Hinweis: Ich hab von Kodi selbst wirklich kaum Ahnung und tu mir schwer einzuschätzen wo der Fehler her kommt. Wenn ich hier falsch bin schick mich einfach weiter.

**Comment by prof-membrane** [comment]
Krypton wird noch nicht unterstützt. Im Moment laufen Vorbereitungen, die das offizielle Krypton Repo und mein Jarvis Repo inkompatibel machen.

**Comment by mfxbe** [comment]
Ah, das erklärt auch warum es vorher funktioniert hat.
