### ISSUE TITLE
CAddonInstallJob[plugin.video.ardmediathek_de]: failed to install dependency script.module.libard

### ISSUE THREAD

**Issue by bequiet88** [prof-membrane/plugin.video.ardmediathek_de#12]
Hey,
Danke für die coole Mediatheken Add-ons.

Ich will im Kodi (17.1) dein Repository per ZIP File installieren (repository.membrane.zip) und kriege im Log den Fehler der oben im Titel steht.

Meine Theorie dahinter ist, dass in "https://github.com/prof-membrane/repository.membrane/blob/master/addons.xml" in Zeile 94 noch Version 0.4.0 verlinkt ist, statt der neuen 0.4.2 von Anfang Januar 2017. Wenn das so ist, kannst du es bitte hochsetzen?

Danke und viele Grüße,
Jochen

**Comment by prof-membrane** [comment]
https://github.com/prof-membrane/plugin.video.zdf_de_lite/issues/13
