### ISSUE TITLE
"Datum auswählen" schlägt fehl

### ISSUE THREAD

**Issue by simonbuehler** [prof-membrane/plugin.video.ardmediathek_de#13]
hi,

habe folgenende backtrace bekommen:

```
but it can't
21:20:40.024 T:8800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('datum',)
                                            Traceback (most recent call last):
                                              File "C:\Users\adidas\AppData\Roaming\Kodi\addons\plugin.video.ardmediathek_de\default.py", line 4, in <module>
                                                libard.list()
                                              File "C:\Users\adidas\AppData\Roaming\Kodi\addons\script.module.libard\lib\libard.py", line 149, in list
                                                l = modes.get(mode,libArdListMain)()
                                              File "C:\Users\adidas\AppData\Roaming\Kodi\addons\script.module.libard\lib\libard.py", line 120, in libArdListChannelDateVideos
                                                url = 'http://www.ardmediathek.de/appdata/servlet/tv/sendungVerpasst?json&kanal='+channels[params['channel']]+'&tag='+params['datum']
                                            KeyError: ('datum',)
                                            -->End of Python script error report<--
21:20:40.035 T:7644   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ardmediathek_de/?channel=SWR%20Fernsehen&mode=libArdListChannelDateVideos&name=Choose%20date
21:20:40.035 T:7644   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ardmediathek_de/?channel=SWR%20Fernsehen&mode=libArdListChannelDateVideos&name=Choose%20date) failed
21:21:18.111 T:7644   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
```

kann leider nicht nach Datum suchen über die Woche hinaus

**Comment by prof-membrane** [comment]
Wird gefixt.

**Comment by yoshimo** [comment]
Das Problem existiert stand 6.1.2017 weiterhin

**Comment by prof-membrane** [comment]
Kann ich nicht nachvollziehen. Der Fehler ist zumindest in meinem Repo nicht vorhanden.

Ich hab das Ticket einfach nicht geschlossen.

**Comment by yoshimo** [comment]
Ist hier vielleicht was veraltet @prof-membrane ?
[kodi.log](https://github.com/prof-membrane/plugin.video.ardmediathek_de/files/1616272/kodi.log)

`script.module.libard v5.1.0 installed
13:07:29.353 T:1942373376  NOTICE: ADDON: plugin.video.ardmediathek_de v5.1.0 installed
`
sah eigentlich gut aus bis zu

`13:29:27.125 T:1456472976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('datum',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ardmediathek_de/default.py", line 4, in <module>
                                                libard.list()
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 144, in list
                                                l = modes.get(mode,libArdListMain)()
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 119, in libArdListChannelDateVideos
                                                url = 'http://www.ardmediathek.de/appdata/servlet/tv/sendungVerpasst?json&kanal='+channels[params['channel']]+'&tag='+params['datum']
                                            KeyError: ('datum',)
                                            -->End of Python script error report<--
13:29:27.138 T:1942373376   ERROR: GetDirectory - Error getting plugin://plugin.video.ardmediathek_de/?channel=Das%20Erste&mode=libArdListChannelDateVideos&name=Datum%20aussuchen
13:29:27.139 T:1942373376   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ardmediathek_de/?channel=Das%20Erste&mode=libArdListChannelDateVideos&name=Datum%20aussuchen) failed
13:30:03.146 T:1942373376  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"`
