### ISSUE TITLE
repository.membrane.zip für Jarvis Zweig

### ISSUE THREAD

**Issue by semilokaleinfachzusammenhaengend** [prof-membrane/plugin.video.ardmediathek_de#14]
Betriebssystem: LibreElec 7.0.2
Kodi Version: 16.1
Add-on Version: *
Bibliothek: *
Bibliothek: *

Hallo Membrane,
ich wollte heute dein Repository (membrane's KODI Add-ons) aus dem Jarvis-Zweig auf meinem Kodi 16.1 einbinden.

Die **repository.membrane.zip** von
https://github.com/prof-membrane/repository.membrane/tree/jarvis
zeigt aber auf den Master-Zweig. Sie ist identisch mit
https://github.com/prof-membrane/repository.membrane/repository.membrane.zip

Ich musste daher in der **addon.xml**  "**master**" durch "**jarvis**" ersetzen, um die älteren Versionen im Kodi Addon Manager gelistet zu bekommen. Wäre nett, wenn du das ZIP entsprechend anpasst.

Danke und Gruß
slez

**Comment by prof-membrane** [comment]
Der Branch sollte eigentlich nur noch die ZIPs enthalten, nichts anderes mehr. Jarvis wird nicht mehr von mir unterstützt.
