### ISSUE TITLE
Kein Installation der Add-On möglich

### ISSUE THREAD

**Issue by speci-man** [prof-membrane/plugin.video.ardmediathek_de#15]
[kodi.txt](https://github.com/prof-membrane/plugin.video.ardmediathek_de/files/764783/kodi.txt)
Hallo Membrane,

konnte des Rebo installieren, aber keines der dort befindlichen Add-Ons. Habe das aktuelle Rebo von hier genommen.
Das Ganze läuft mit LibreELEC release: RPi2.arm-7.95.2.
Kodi-Log im Anhang.
Hast du eine Idee warum nicht?

**Comment by prof-membrane** [comment]
Mit meinem Repo ist alles ok. Du kannst höchstens das Repo löschen und neu installieren. Mehr Tips kann ich nicht geben.

Im offiziellen Repo sind auch alle Add-ons zu finden.
