### ISSUE TITLE
Favoriten hinzufügen

### ISSUE THREAD

**Issue by marcelscode** [prof-membrane/plugin.video.ardmediathek_de#17]
DIe Liste an Sendungen ist ewig lang (gilt auch für die anderen Mediatheken), man muss lange scrollen, bis man endlich die Sendung findet, die man sucht. Andere Addons bieten hier die Möglichkeit, innerhalb des Addons Favoriten anzulegen, um schnell auf die bevorzugten Sendungen zuzugreifen. Eine frühere Version dieses Addons konnte das auch.

Es wäre schön, wenn dieses Features wieder hinzugefügt wird.

**Comment by prof-membrane** [comment]
Entweder nutzt man dazu die internen Favoriten oder ein weiteres Add-on. Ein solches Feature in dem Add-on direkt zu implementieren ist sinnlos.

**Comment by marcelscode** [comment]
Einige Add-ons haben gernau das, andere Entwickler halten dieses Feature also keineswegs für sinnlos.

Unabhängig von deiner Meinung zu diesem Feature Request kann man aber kaum bestreiten, dass deine Mediathek-Addons ein großes Usability Problem haben: Man scrollt sich zu Tode. Das ist beim ARD Add-on schon schlimm, die Unithek ist deswegen schlicht unbedienbar. Add-on Favoriten würden dabei helfen, weil man sich dann sein eigenes Subset zusammenstellen kann, daher kommt auch mein Wunsch. Natürlich sind an der Stelle auch andere Konzepte denkbar. Nachdem du meinen Vorschlag so abgebügelt hast, bin ich mal gespannt, was da kommt...

**Comment by prof-membrane** [comment]
Soll ich jetzt für jedes meiner Add-ons Favoriten implementieren? Ich habe nie geschrieben, dass Favoriten keine Verwendung haben. Meine Add-ons unterstützen schon immer die globale Favoritenliste.

Derartige Funktionen haben nichts im Add-on Code verloren. Dafür ist Kodi selbst zuständig, ansonsten macht man sich nur (sinnlose) Mehrarbeit. Wenn jetzt jeder Entwickler mit seiner eigenen Implementierung daherkommt braucht man von Usability auch nicht mehr reden.

Die langen Listen sind mit Kodi sehr schnell scrollbar. Zum gewünschten Buchstaben kann man bequem per Fernbedienung springen und die Filtersuche erlaubt ein schnelles Auffinden von Sendungen. Für mich ist dies wesentlich schneller und effektiver als eine Vorsortierung nach Buchstaben. Eine Buchstabenauswahl liegt auf meiner Prioritätenliste weit unten.
