### ISSUE TITLE
Option für Videoqualität?

### ISSUE THREAD

**Issue by maikmerten** [prof-membrane/plugin.video.ardmediathek_de#18]
Danke für das wunderbare Addon - nutze es auf einem RPi mit Kodi 17.1!

Ich meine mich zu erinnern, in deutlich älteren Addon-Versionen eine Option für die Videoqualtität gehabt zu haben, um auch bei langsamer Internetverbindung Bufferpausen zu vermeiden.

Aktuell scheint das Addon keine Einstellungen diesbezüglich zu haben. Sollte ich mich nicht irren: Es wäre schön, eine Option zu haben, die Videoqualität auszuwählen. Ansonsten bitte ich die Störung zu entschuldigen!

**Comment by prof-membrane** [comment]
Alle meiner Add-ons folgen den globalen Einstellungen - so muss man nicht jedes Add-on manuell einstellen.

https://github.com/prof-membrane/repository.membrane/wiki/Videoqualit%C3%A4t-der-Add-ons#qualit%C3%A4tsauswahl
