### ISSUE TITLE
Feature Merkliste?

### ISSUE THREAD

**Issue by strikerboy1024** [prof-membrane/plugin.video.ardmediathek_de#2]
Wäre die Funktion Merkliste http://www.ardmediathek.de/merkliste im Addon ein Thema für dich? Das ZDF hat diese Funktion auch in ihrer Mediathek.

**Comment by prof-membrane** [comment]
Ich hab diese Funktion noch nie verstanden. Für Bookmarks gibt es ja den Browser, da braucht es keine extra Unterfunktion auf der Webseite.

Bei Kodi selbst gibt es auch die Favoriten, die dies übernehmen sollten. Andernfalls kann man auch das Add-on von Slix nutzen (ich hab mich da noch nicht mit beschäftigt). 

Zusammengefasst: im Add-on selbst wird es keinen Merkliste geben, der Support dafür muss extern durch den Core/anderes Add-on kommen.

**Comment by strikerboy1024** [comment]
Ich finde solche watch-it-later-Listen im Addon selbst (Amazon, Youtube, Maxdome...) ganz dankbar.  Die Kodi Favoritenliste wird da schnell voluminös/unübersichtlich, wenn man mehrere VOD-Addons nutzt. Verwende die auch eher um Verzeichnisse zu verlinken und keine einzelnen Videos.

Das Bookmark-Addon von SLIX ist eine gute bzw. die bessere Alternative, ich nutze es momentan auch hierfür. Hatte mich nur mal interessiert, wie du zu einer Merkliste im Addons selbst zu stehst.
