### ISSUE TITLE
Some videos won't play

### ISSUE THREAD

**Issue by spielzeugland** [prof-membrane/plugin.video.ardmediathek_de#20]
Thanks for the great work making public TVstations available in Kodi!

Since some time some videos won't play anymore:
```
ERROR: GetDirectory - Error getting //wdradaptiv-vh.akamaihd.net/i/medp/ondemand/weltweit/fsk0/148/1481223/,1481223_16981035,1481223_16981033,1481223_16981037,1481223_16981032,1481223_16981034,1481223_16981036,.mp4.csmil/
ERROR: Previous line repeats 1 times.
ERROR: CVideoPlayer::OpenInputStream - error opening [//wdradaptiv-vh.akamaihd.net/i/medp/ondemand/weltweit/fsk0/148/1481223/,1481223_16981035,1481223_16981033,1481223_16981037,1481223_16981032,1481223_16981034,1481223_16981036,.mp4.csmil/master.m3u8]
```
(The URL mentions WDR but was found through ARD AddOn, although I am not sure whether this makes a difference).
For me it looks like the protocol in the URL is missing. Would be happy if I could help you on this. Is there some documentation or overview about your AddOns and how they work. I haven't looked into your code yet.

**Comment by white-gecko** [comment]
I also have problems when I want to play "Die Sendung mit der Maus". The Kodi interface just shortly shows the spinner and then returns to the list of the available program.

**Comment by white-gecko** [comment]
If you use youtube-dl it extracts in my case:

    http://wdradaptiv-vh.akamaihd.net/i/medp/ondemand/weltweit/fsk0/148/1484158/,1484158_17010957,1484158_17010960,1484158_17010959,1484158_17010956,1484158_17010958,.mp4.csmil/index_2_av.m3u8?null=0

as URL the first part is the same, the numbers differ and the end is `,.mp4.csmil/master.m3u8` in your case, while it is `,.mp4.csmil/index_2_av.m3u8?null=0`. I don't know if this is an important difference …

**Comment by prof-membrane** [comment]
The ARD API is pretty broken, it just delivers the URL like this. A patch should appear soon in my repository.

I can't recommend the ARD Mediathek. It is very messy from an internal viewpoint. There are multiple shortcommings (fewer available videos, low video bitrate, no descriptions, missing subtitles, etc). The individual add-ons are better in almost every regard. You could use the Unithek if you want a central, easy to use Mediathek.

There is some general documentation available at my wiki (https://github.com/prof-membrane/repository.membrane/wiki/API-Quellen-der-einzelnen-Add-ons). It is a short overview about the APIs used by my scrapers. If you want to help me with the add-on development, I could write a bit about the goals/ideas behind my scrapers/add-ons.

**Comment by white-gecko** [comment]
If I understand it correctly you recommend to use [Das Erste](http://kodi.wiki/view/Add-on:Das_Erste_Mediathek), [MDR Mediathek](http://kodi.wiki/view/Add-on:MDR_Mediathek), [WDR Mediathek](http://kodi.wiki/view/Add-on:WDR_Mediathek), … instead.

Thanks for the pointer.

**Comment by prof-membrane** [comment]
Done.
