### ISSUE TITLE
Installation des Repo AddOns geht nicht

### ISSUE THREAD

**Issue by JPT77** [prof-membrane/plugin.video.ardmediathek_de#21]
Hallo, 

leider gibt es keinen Punkt für das Repo selbst. o.O
Ich habe es aus dem [ZIP file](https://github.com/prof-membrane/repository.membrane/raw/master/repository.membrane.zip) installiert. es gab eine Fehlermeldung bezüglich fehlender Voraussetzungen mit der Frage, ob aktivieren oder nicht.
Es ist nun installiert, aber ich kann nur einen EPG Service installieren. Die Mediatheken in sind nicht da (Video Addons ist leer).

Den Menüpunkt Unknown Sources wie [hier](http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files) beschrieben gibt es nicht. Es gibt Settings/System und Settings/Addons aber kein Settings/system/addons, auch nicht im Expertenmodus.

OpenElec 7.0.1 auf Wetek Play
(OpenElec 8.0.3 läuft leider nicht, sonst hätte ich mal aktualisiert)
Kodi 16.1 Git:c1c4b9e
kernel: Linux ARM 32-bit version 3.10.99

Repo Addon Version 2.0.0 oder 1.9.0... widersprechende Angaben im ZIP.

In .kodi/temp/kodi.log find ich nichts konkretes. soll ich die Logs gesamt anhängen?
das wird ja nichts damit zu tun haben?
`WARNING: CSkinInfo: failed to load skin settings`

Was hat es mit den Bibliotheken libMediathek2 usw auf sich?

ne Idee was die Ursache sein könnte?

Vielen Dank

**Comment by prof-membrane** [comment]
Kodi 16 wird nicht unterstützt.

**Comment by JPT77** [comment]
OK. Habe LibreElec 8.0.2 installiert und dort ist dein Repo schon integriert.
