### ISSUE TITLE
support for hd streams

### ISSUE THREAD

**Issue by ed76** [prof-membrane/plugin.video.ardmediathek_de#24]
it seems there are hd streams avaiable (e.g. „tatort“) but the addon chooses a lower quality.

**Comment by prof-membrane** [comment]
The add-on does not choose the quality of the stream. Kodi itself picks the stream, limited by the bandwidth adjustable in the settings. 

Some seperate Mediatheken/CDNs may provide a better version at their portal, inaccessable via the ARD Mediathek. Yes, I could add some dirty hacks in an attempt to improve the video quality, but this is error prone and not suitable. Go and write to the ARD if you have a problem with that.

If you spot a difference between the quality offered on the website and my add-on, post the link in this issue.
