### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by JohnPlayerSpecial2018** [prof-membrane/plugin.video.ardmediathek_de#27]
https://www.dwdl.de/nachrichten/68534/neue_ardmediathek_kommt_noch_in_diesem_jahr/
https://beta.ardmediathek.de/ard/

**Comment by prof-membrane** [comment]
Ich hab schon seit längeren eine Demo geschrieben. Ein neues Add-on wird in den nächten Monaten folgen.
