### ISSUE TITLE
Frage zu WDR Inhalt

### ISSUE THREAD

**Issue by strikerboy1024** [prof-membrane/plugin.video.ardmediathek_de#3]
Über die ARD Mediathek lassen sich zur Sendung "Zimmer Frei" nur einzelne, kleine Beiträge abspielen:
http://www.ardmediathek.de/tv/Zimmer-frei/Sendung?documentId=7535548&bcastId=7535548

Die vollen Sendungen bekommt man nur über die angezeigte Verlinkung zur WDR Mediathek
http://www1.wdr.de/fernsehen/zimmer-frei/index.html

Ist ein Einbau denkbar oder gehört dies in ein eigenes WDR Addon? Ich meine mich zu erinnern, dass ich früher ganze Sendungen von "Zimmer Frei" über die ARD Mediathek gelistet bekam, aber kann mich da auch irren.

**Comment by prof-membrane** [comment]
Ich möchte in den einzelnen Mediatheken nur das anbieten, was auch über die Webseite zu erreichen ist. Allerdings ist die WDR Mediathek ein Kandidat für ein eigenes Add-on/eine Integration in die Unithek. Mal schauen ob ich mich daran versuche. Der Aufbau der Webseite ist schrecklich und viel Zeit hab ich im Moment auch nicht ;).

**Comment by strikerboy1024** [comment]
Hab ich mir schon gedacht. Finde ich auch schlüssig vom Ansatz nichts dazuzumogeln, was nicht explizit zur ARD Mediathek gehört. Hatte mich nur gerade geärgert, die gewünschte ganze Sendung nicht sehen zu können. Ein eigenes WDR Addon wäre natürlich oberklasse, keine Frage...

**Comment by prof-membrane** [comment]
Ich wollte gerade die HbbTV Mediathek dafür nehmen - allerdings haben ein paar Funkhäuser - inkl. WDR - massive Probleme. Die werfen diverse Fehler wie 503.

**Comment by prof-membrane** [comment]
Ab heute gibt es auch die WDR Mediathek als Add-on - erst einmal nur mit A-Z Auflistung. Das dürfte aber schon fast alle Videos abdecken, die es nicht in der ARD Mediathek gibt.
