### ISSUE TITLE
Can't install *help wanted*

### ISSUE THREAD

**Issue by Xposhox** [prof-membrane/plugin.video.ardmediathek_de#4]
Not able to install anything from the Reposity.
Im using the latest stable version of Kodi on a fire tv stick.
Here a part from the log...

```

CCurlFile::Open failed with code 404 for http://github.com/prof-membrane/repository.membrane/raw/master/script.module.libMediathek/script.module.libMediathek-1.1.7.zip
16:21:52 T:1252050344   ERROR: CAddonInstallJob[script.module.libMediathek]: failed to download special://home/addons/packages/script.module.libMediathek-1.1.7.zip
16:21:52 T:1252050344   ERROR: CAddonInstallJob[script.module.libArd]: failed to install dependency script.module.libMediathek
16:21:52 T:1252050344   ERROR: CAddonInstallJob[plugin.video.ardmediathek_de]: failed to install dependency script.module.libArd
```

Cant find an solution or an guide to install. Therefore I'm posting here.
Sorry.

Thanks in advance!
Xposhox

**Comment by prof-membrane** [comment]
The information pointing to my repo is not up to date, the libMediathek is at version 1.1.10 now (and was at 1.1.9 before). Just refresh my repo and you will be able to install the add-on. 

Leave me a message if this resolves your problem.

I will keep previous versions in the repo to ensure that this issue won't happen again.

**Comment by Xposhox** [comment]
Works like a charm now!

## Updated the Repo and everything works fine now.

So - hatte irgendwie übersehen das ich auch einfach in deutsch hätte posten können.
Vielen Dank für die schnelle Hilfe und Umsetzung 👍 
Dann kann ich ja jetzt die Sendung schauen die ich schauen wollte :)

**Comment by prof-membrane** [comment]
Das nerft mich schon länger an Kodi. Es wird vor der Installation eines Add-ons nicht gecheckt, ob evntl. eine neuere version vorhanden ist. Im Moment aktualisiere ich die Add-ons fast täglich.

Bald werden die Add-ons sowieso über das offizielle Repo zugänglich sein, wobei diese dann nicht so oft aktualisiert werden wie hier.
