### ISSUE TITLE
Stream Buffer funktioniert nicht

### ISSUE THREAD

**Issue by kein0r** [prof-membrane/plugin.video.ardmediathek_de#5]
Starte ich einen der ARD streams (gleiches gilt für die anderen auch) wird der Stream nicht, wie im alten plugin, gepuffert. Bei langsamen Leitungen und da scheinbar immer der bestmöglichste stream rausgesucht wird macht dies das Anschauen der Streams unmöglich.
Es hilft auch nicht Pause zu drücken und 1-2 Minuten zu warten. Bei anderen plugins steht beim Start zunächst immer "Buffering x%" oben rechts.

Plugin 4.9.2
Kodi 15.2
Rasperry

**Comment by kein0r** [comment]
[kodi.log.zip](https://github.com/prof-membrane/plugin.video.ardmediathek_de/files/512913/kodi.log.zip)

**Comment by prof-membrane** [comment]
Kodi sucht die Streams selbst aus. Wenn in den Netzwerkeinstellungen die maximale Bitrate nicht eingestellt ist wird folglich die beste Qualität genommen. Steht auch im Wiki.

**Comment by kein0r** [comment]
Danke für die schnelle Antwort. Das Problem ist das ich damit alle Streams begrenze. Ich lebe im Ausland, lokale Streams hätte ich gerne weiterhin in bestmöglicher Qualität, nur die nicht lokalen eben aufgrund der Verbindungsqualität wenn möglich  mit reduzierter Qualität in jedem Fall aber mit Buffering. Beides war mit der bisherigen App möglich.

**Comment by prof-membrane** [comment]
Sorry, dann kann ich dir auch nicht helfen. Die Bitrate per Add-on zu limitieren macht zu viel Arbeit. Patches sind natürlich willkommen.

Lieber macht man es gleich richtig und implementiert HLS in Kodi.

**Comment by kein0r** [comment]
Mir geht es primär gar nicht um die Bitrate. Mir ging es hier um das fehlende Buffering. Selbst wenn ich die Bitrate auf 20kbps reduziere kann das video stocken, da es keinen buffer gibt und somit kurzfristige Leitungsprobleme nicht abgefedert werden können.
Das buffering ist da, das alte plugin hat es verwendet. Es müsste also nur in dem neuen auch verwendet werden.

**Comment by prof-membrane** [comment]
Damit hat mein Add-on nichts zu tun. Darauf hab ich keinen Einfluss. Klär das am besten im Kodi Forum.

**Comment by kein0r** [comment]
Warum ging das dann bisher? Im alten ARD plugin, wie auch in anderen plugins, steht immer oben rechts "Bufferin x%". Ohne das Feature ist das plugin nur bei sehr guten Letungen wirklich nutzbar.

**Comment by prof-membrane** [comment]
Die Add-ons nutzen HLS Streams.

**Comment by kein0r** [comment]
Könnte man dann diese, evtl. optional, auch in diesem Plugin verwenden. Wie gesagt aktuell sind die Plugins bei schwankender Leitungsqualität nicht nutzbar.

**Comment by prof-membrane** [comment]
Klar, wenn es jemand einbaut.

**Comment by kein0r** [comment]
Kann ich irgendwo einen feature request eintragen oder kann evtl. diese ticket offen bleiben bis es jemand integriert. So jedenfalls ist das Addon nicht nutzbar.

**Comment by prof-membrane** [comment]
Mach ein neues Ticket auf, mit dem Ziel die *.mp4 Streams per Option auszuliefern.

Allerdings kann ich es nicht stark genug betonen, dass Kodi HLS Streams besser handhaben sollte. Alle Add-ons der ÖR Sender setzen auf HLS, teilweise ohne Alternative.
