### ISSUE TITLE
libArd Fehler

### ISSUE THREAD

**Issue by Kei4** [prof-membrane/plugin.video.ardmediathek_de#6]
Servus,

wenn ich das AddOn auswähle, startet es. Aber sobald man ein Untermenü (z.B. "Neu") auswählt, läd es etwas und man bekommt dann ein "libArd Fehler".

Kodi/OSMC (auf nem Raspberry) ist bereits auf der neusten Version, das brachte leider nichts.
ARD Mediathek Addon ist auf 4.9.2

Danke schon mal! :-)
Greetz Kei

**Comment by prof-membrane** [comment]
Hab ich schon vor Tagen repariert aber vergessen hochzuladen. Geht wieder.
