### ISSUE TITLE
Probleme mit Version 4.9.3

### ISSUE THREAD

**Issue by ed76** [prof-membrane/plugin.video.ardmediathek_de#8]
hallo,
seit dem update des ard addons auf version 4.9.3 funktioniert die suche nicht mehr. weiterhin sind nun deutlich weniger sendungen über das addon verfügbar als mit der vorgängerversion (bsp. "die pierre m krause show" oder "mörderisches tal - pregau" fehlt der erste von vier teilen, obwohl der aber in der ard mediathek noch bis 1.4. verfügbar ist.

**Comment by prof-membrane** [comment]
Das Add-on kann noch nicht die "Nächste Seite" darstellen, darum sind die Ergebnisse auf 12 begrenzt. Dazu wird bald ein Update kommen.

Bei dem Krimi werden die Teile angezeigt, die auch online sind.
